// <auto-generated />
using System;
using CharityDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CharityDB.net5.Migrations
{
    [DbContext(typeof(net5Context))]
    [Migration("20220401002219_intitalcreate")]
    partial class intitalcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CharityDB.net5.Models.donations", b =>
                {
                    b.Property<int>("donationsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<string>("Banktype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionID")
                        .HasColumnType("int");

                    b.Property<string>("TransactionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("donationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("donationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("donationPrice")
                        .HasColumnType("int");

                    b.Property<int?>("itemsId")
                        .HasColumnType("int");

                    b.Property<int?>("membersId")
                        .HasColumnType("int");

                    b.HasKey("donationsID");

                    b.HasIndex("itemsId");

                    b.HasIndex("membersId");

                    b.ToTable("donations");
                });

            modelBuilder.Entity("CharityDB.net5.Models.items", b =>
                {
                    b.Property<int>("itemsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("clothes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("food")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("itemsId");

                    b.ToTable("items");
                });

            modelBuilder.Entity("CharityDB.net5.Models.members", b =>
                {
                    b.Property<int>("membersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("membersName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("membersId");

                    b.ToTable("members");
                });

            modelBuilder.Entity("CharityDB.net5.Models.donations", b =>
                {
                    b.HasOne("CharityDB.net5.Models.items", null)
                        .WithMany("donations")
                        .HasForeignKey("itemsId");

                    b.HasOne("CharityDB.net5.Models.members", null)
                        .WithMany("Donations")
                        .HasForeignKey("membersId");
                });

            modelBuilder.Entity("CharityDB.net5.Models.items", b =>
                {
                    b.Navigation("donations");
                });

            modelBuilder.Entity("CharityDB.net5.Models.members", b =>
                {
                    b.Navigation("Donations");
                });
#pragma warning restore 612, 618
        }
    }
}
